### ISSUE TITLE
Use existing graphql endpoint doesn't work

### ISSUE THREAD

**Issue by RecoX** [howtographql/react-apollo#67]
Clean installation using the endpoint generated before with https://github.com/howtographql/graphql-js

Is not working

```
➜  server git:(master) ✗ yarn start
yarn run v1.12.3
$ node src/index.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at /Users/lucasrecoaro/react-apollo/server/node_modules/graphql-yoga/dist/index.js:344:28
    at new Promise (<anonymous>)
    at GraphQLServer.start (/Users/lucasrecoaro/react-apollo/server/node_modules/graphql-yoga/dist/index.js:342:16)
    at Object.<anonymous> (/Users/lucasrecoaro/react-apollo/server/src/index.js:27:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
error Command failed with exit code 1.
```

```
# Specifies the HTTP endpoint of your Prisma API.
#endpoint: ''
endpoint: https://us1.prisma.sh/lucas-3856c0/ao-web-indexer/ao-web-indexer/dev

# Defines your models, each model is mapped to the database as a table.
datamodel: datamodel.prisma

# Specifies the language and directory for the generated Prisma client.
generate:
  - generator: javascript-client
    output: ../src/generated/prisma-client

# Ensures Prisma client is re-generated after a datamodel change.
hooks:
  post-deploy:
    - prisma generate
```
